-- 106_hr_biometric_sync.sql
--
-- Lets an on-premise biometric punch receiver (attendance-api/adms-lite.js,
-- running on the office PC behind NAT) deliver daily attendance totals into
-- hr.attendance_daily on the cloud API.
--
-- The office PC has no public IP, so the cloud can never call it. Every
-- exchange is therefore initiated BY the office PC:
--
--   1. It POSTs daily totals to /api/hr/biometric/sync on a timer.
--   2. When an HR user clicks "Sync now" for a date range, the click only
--      writes a row into hr.attendance_sync_job. The office PC picks that job
--      up on its next poll of /api/hr/biometric/jobs and pushes the range.
--
-- Four tables:
--   biometric_device_token       - who is allowed to push, and as which tenant
--   attendance_biometric_staging - every row ever received, matched or not
--   biometric_pin_map            - device PIN -> employee, when the PIN is not
--                                  the employee_code
--   attendance_sync_job          - the "Sync now" queue
--
-- The staging table is the important one. Device PINs at the first site
-- (TWMSDXB01..TWMSDXB31 plus a few bare integers) match no employee_code, and
-- an earlier iteration of this integration silently discarded ~499 real
-- punches because it dropped rows whose PIN it could not resolve. Nothing is
-- dropped now: unresolved rows land in staging as 'unmatched' and are replayed
-- into attendance_daily the moment someone maps the PIN.

BEGIN;

-- ── Device tokens ────────────────────────────────────────────────────────────
-- Deliberately NOT keyed by company: the token is what identifies the tenant,
-- so it has to be looked up before company_id is known. The bearer secret is
-- never stored - only its SHA-256 hex digest, so a database read cannot be
-- replayed against the API.
CREATE TABLE IF NOT EXISTS hr.biometric_device_token (
  token_id      SERIAL       PRIMARY KEY,
  company_id    INTEGER      NOT NULL,
  branch_id     INTEGER      NOT NULL,
  token_hash    CHAR(64)     NOT NULL UNIQUE,
  label         VARCHAR(80),
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  last_seen_at  TIMESTAMPTZ,
  last_seen_ip  VARCHAR(64),
  last_sync_at  TIMESTAMPTZ,
  last_sync_rows INTEGER     NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_biometric_device_token_tenant
  ON hr.biometric_device_token (company_id, branch_id)
  WHERE is_active;

-- ── PIN -> employee map ──────────────────────────────────────────────────────
-- Resolution order at sync time is: this table first, then
-- employee_master.employee_code = device PIN. The map exists because
-- employee_code is generated by the EMPLOYEE doc sequence (EMP-00001) while
-- the device PIN is whatever the installer typed into the terminal.
CREATE TABLE IF NOT EXISTS hr.biometric_pin_map (
  company_id   INTEGER     NOT NULL,
  branch_id    INTEGER     NOT NULL,
  device_pin   VARCHAR(64) NOT NULL,
  employee_id  INTEGER     NOT NULL,
  device_name  VARCHAR(120),
  mapped_by    INTEGER,
  mapped_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (company_id, branch_id, device_pin)
);

CREATE INDEX IF NOT EXISTS ix_biometric_pin_map_employee
  ON hr.biometric_pin_map (company_id, branch_id, employee_id);

-- ── Staging ──────────────────────────────────────────────────────────────────
-- One row per (device PIN, work_date). Re-pushing the same day overwrites the
-- times rather than appending, so the office PC can safely re-send a rolling
-- window on every timer tick.
--
-- status:
--   unmatched - PIN resolves to no employee. Waiting for a mapping.
--   applied   - resolved and written into hr.attendance_daily.
--   ignored   - explicitly dismissed by an HR user (visitor, test punch).
--
-- first_in/last_out are TIME here but TIMESTAMP on hr.attendance_daily. That is
-- deliberate: the device reports a clock time against a date it also sends, so
-- TIME is the honest storage. attendance_daily uses TIMESTAMP because the ERP's
-- manual Punch In/Out buttons write a full Date. The repository adds work_date
-- back on when it moves a row across.
CREATE TABLE IF NOT EXISTS hr.attendance_biometric_staging (
  company_id    INTEGER      NOT NULL,
  branch_id     INTEGER      NOT NULL,
  staging_id    INTEGER      NOT NULL,
  device_pin    VARCHAR(64)  NOT NULL,
  device_name   VARCHAR(120),
  device_sn     VARCHAR(64),
  work_date     DATE         NOT NULL,
  first_in      TIME,
  last_out      TIME,
  hours         NUMERIC(6,2),
  punches       INTEGER      NOT NULL DEFAULT 0,
  status        VARCHAR(20)  NOT NULL DEFAULT 'unmatched',
  employee_id   INTEGER,
  received_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  applied_at    TIMESTAMPTZ,
  PRIMARY KEY (company_id, branch_id, staging_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_biometric_staging_pin_date
  ON hr.attendance_biometric_staging (company_id, branch_id, device_pin, work_date);

CREATE INDEX IF NOT EXISTS ix_biometric_staging_unmatched
  ON hr.attendance_biometric_staging (company_id, branch_id, device_pin)
  WHERE status = 'unmatched';

-- ── Sync job queue ───────────────────────────────────────────────────────────
-- The ERP "Sync now" button writes here; the office agent drains it. Latency
-- is one poll interval (~30s), which is the price of never exposing the office
-- PC to inbound traffic.
CREATE TABLE IF NOT EXISTS hr.attendance_sync_job (
  company_id     INTEGER      NOT NULL,
  branch_id      INTEGER      NOT NULL,
  job_id         INTEGER      NOT NULL,
  from_date      DATE         NOT NULL,
  to_date        DATE         NOT NULL,
  status         VARCHAR(20)  NOT NULL DEFAULT 'pending',
  requested_by   INTEGER,
  requested_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  claimed_at     TIMESTAMPTZ,
  completed_at   TIMESTAMPTZ,
  rows_received  INTEGER      NOT NULL DEFAULT 0,
  rows_matched   INTEGER      NOT NULL DEFAULT 0,
  rows_staged    INTEGER      NOT NULL DEFAULT 0,
  error_message  TEXT,
  PRIMARY KEY (company_id, branch_id, job_id)
);

-- Partial index: the agent's poll is "give me pending jobs for my tenant",
-- which runs every 30 seconds forever.
CREATE INDEX IF NOT EXISTS ix_attendance_sync_job_pending
  ON hr.attendance_sync_job (company_id, branch_id, requested_at)
  WHERE status IN ('pending', 'claimed');

-- ── Provenance on attendance_daily ───────────────────────────────────────────
-- Distinguishes a row the device produced from one an HR user typed. Without
-- it, a re-sync cannot tell whether overwriting first_in/last_out is safe.
ALTER TABLE hr.attendance_daily
  ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'manual';

ALTER TABLE hr.attendance_daily
  ADD COLUMN IF NOT EXISTS device_pin VARCHAR(64);

ALTER TABLE hr.attendance_daily
  ADD COLUMN IF NOT EXISTS synced_at TIMESTAMPTZ;

COMMIT;
